In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5664, 1146, 6973, 8069],
 [5664, 1146, 6973, 2328],
 [5664, 694, 6973, 1097],
 [1127, 5685, 4120, 4317, 3777],
 [1127, 5685, 4120, 4317, 1527],
 [1601, 5664, 9463, 6973, 4348],
 [3295, 7012, 5607, 4317]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5664 1146 6973 8069]
 [   0    0    0    0 5664 1146 6973 2328]
 [   0    0    0    0 5664  694 6973 1097]
 [   0    0    0 1127 5685 4120 4317 3777]
 [   0    0    0 1127 5685 4120 4317 1527]
 [   0    0    0 1601 5664 9463 6973 4348]
 [   0    0    0    0 3295 7012 5607 4317]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 169ms/step


array([[[-1.53749213e-02,  1.21819973e-02,  1.53410174e-02,
         -4.19517048e-02,  4.02024128e-02, -4.64222692e-02,
          2.59979852e-02,  2.94897817e-02,  4.90839966e-02,
         -2.98646223e-02],
        [-1.53749213e-02,  1.21819973e-02,  1.53410174e-02,
         -4.19517048e-02,  4.02024128e-02, -4.64222692e-02,
          2.59979852e-02,  2.94897817e-02,  4.90839966e-02,
         -2.98646223e-02],
        [-1.53749213e-02,  1.21819973e-02,  1.53410174e-02,
         -4.19517048e-02,  4.02024128e-02, -4.64222692e-02,
          2.59979852e-02,  2.94897817e-02,  4.90839966e-02,
         -2.98646223e-02],
        [-1.53749213e-02,  1.21819973e-02,  1.53410174e-02,
         -4.19517048e-02,  4.02024128e-02, -4.64222692e-02,
          2.59979852e-02,  2.94897817e-02,  4.90839966e-02,
         -2.98646223e-02],
        [ 4.49731015e-02,  2.18639262e-02, -2.92803291e-02,
         -5.22136688e-04, -4.20265682e-02, -3.76882330e-02,
         -2.91995890e-02, -2.47868057e-02, -3.467115

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 5664, 1146, 6973, 8069])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 77ms/step


array([[-0.01537492,  0.012182  ,  0.01534102, -0.0419517 ,  0.04020241,
        -0.04642227,  0.02599799,  0.02948978,  0.049084  , -0.02986462],
       [-0.01537492,  0.012182  ,  0.01534102, -0.0419517 ,  0.04020241,
        -0.04642227,  0.02599799,  0.02948978,  0.049084  , -0.02986462],
       [-0.01537492,  0.012182  ,  0.01534102, -0.0419517 ,  0.04020241,
        -0.04642227,  0.02599799,  0.02948978,  0.049084  , -0.02986462],
       [-0.01537492,  0.012182  ,  0.01534102, -0.0419517 ,  0.04020241,
        -0.04642227,  0.02599799,  0.02948978,  0.049084  , -0.02986462],
       [ 0.0449731 ,  0.02186393, -0.02928033, -0.00052214, -0.04202657,
        -0.03768823, -0.02919959, -0.02478681, -0.03467115,  0.01375196],
       [ 0.03688333,  0.03415233,  0.00951257, -0.03105638, -0.02392313,
        -0.0237166 ,  0.00961976,  0.01716434, -0.03653512, -0.04529424],
       [-0.00185645,  0.0289931 ,  0.03236831,  0.03671695,  0.0183974 ,
         0.00225413,  0.00801672, -0.04972248